- hosts: all
  gather_facts: yes
  become: yes
  become_method: sudo
  roles:
  - base

# - hosts: k3s_cluster
#  become: yes
#  roles:
#  - k3s

# - hosts: controlplane
#  become: yes
#  roles:
#  - k3s/controlplane

# - hosts: node
#   become: yes
#   roles:
#   - k3s/node

