- hosts: all
  gather_facts: yes
  become: yes
  become_method: sudo
  roles:
  - base

# - hosts: k3s_cluster
#  become: yes
#  roles:
#  - k3s

- hosts: controlplanes
  become: yes
  roles:
 - k3s/controlplane

# - hosts: nodes
#   become: yes
#   roles:
#   - k3s/nodes

