- hosts: all
  gather_facts: yes
  become: yes
  become_method: sudo
  roles:
  - base

- hosts: controlplanes
  become: yes
  become_method: sudo
  serial: 1
  roles:
  - k3s/controlplane

- hosts: nodes
  become: yes
  become_method: sudo
  roles:
  - k3s/node