---

- name: Check if Cilium CLI is installed
  register: cilium_cli_installed
  command: which cilium
  failed_when: cilium_cli_installed.rc >= 2

- name: Check Cilium CLI version
  register: cilium_cli
  command: cilium version | grep -qw {{ cilium_cli_version }}
  when: cilium_cli_installed.rc == 0
  failed_when: cilium_cli.rc >= 2

- name: Download Cilium CLI
  register: download_cilium_cli
  shell: |
    curl -L --remote-name-all https://github.com/cilium/cilium-cli/releases/download/{{ cilium_cli_version }}/cilium-linux-amd64.tar.gz;
    curl -L --remote-name-all https://github.com/cilium/cilium-cli/releases/download/{{ cilium_cli_version }}/cilium-linux-amd64.tar.gz.sha256sum
    sha256sum --check cilium-linux-amd64.tar.gz.sha256sum;
    tar xzvfC cilium-linux-amd64.tar.gz /usr/local/bin;
  when:
  - cilium_cli_installed.rc == 1 or cilium_cli.rc == 1

- name: Check if Cilium is deployed
  register: cilium_deployed
  command: "cilium status | grep Cilium: | awk '{ print $4 }' | grep -wq OK"
  when:
  - cilium_cli_installed.rc == 0 or download_cilium_cli.rc == 0
  failed_when: 
  - cilium_deployed.rc >= 2

- name: Deploy Cilium
  shell: |
    export KUBECONFIG=/etc/rancher/k3s/k3s.yaml;
    cilium install --version {{ cilium_version }} {{ extra_cilium_args | default("") }};
  when:
  - (cilium_cli_installed.rc == 0 or download_cilium_cli.rc == 0) and cilium_deployed.rc == 1
  