---

- name: Check if Cilium CLI is installed
  command: cilium version | grep -qw {{ cilium_cli_version }}
  register: cilium_cli_installed
  ignore_errors: yes

- name: Download Cilium CLI
  shell: |
    curl -L --remote-name-all https://github.com/cilium/cilium-cli/releases/download/{{ cilium_cli_version }}/cilium-linux-amd64.tar.gz{,.sha256sum};
    sha256sum --check cilium-linux-amd64.tar.gz.sha256sum;
    tar xzvfC cilium-linux-amd64.tar.gz /usr/local/bin;
  when:
  - cilium_cli_installed.rc != 0

- name: Deploy Cilium
  shell: |
    export KUBECONFIG=/etc/rancher/k3s/k3s.yaml;
    cilium install --version {{ cilium_version }} {{ extra_cilium_args | default("") }};
  when:
  - cilium_cli_installed.rc == 0
  