---

- name: Check if Cilium is installed
  shell: |
    kubectl get deployment -n kube-system cilium-operator
  register: cilium_installed

- name: Download Cilium CLI
  shell: |
    curl -L --remote-name-all https://github.com/cilium/cilium-cli/releases/download/{{ cilium_cli_version }}/cilium-linux-amd64.tar.gz{,.sha256sum};
    sha256sum --check cilium-linux-amd64.tar.gz.sha256sum;
    tar xzvfC cilium-linux-amd64.tar.gz /usr/local/bin;
  when:
  - cilium_installed.rc != 0

- name: Deploy Cilium
  shell: |
    export KUBECONFIG=/etc/rancher/k3s/k3s.yaml;
    cilium install --version {{ cilium_version }} {{ extra_cilium_args | default("") }};
  when:
  - cilium_installed.rc != 0
  