---

- name: Check if Cilium CLI is installed
  command: which cilium
  register: cilium_cli_installed

- name: Check Cilium CLI version
  command: cilium version | grep -qw {{ cilium_cli_version }}
  register: cilium_cli
  when: cilium_cli_installed.rc == 0

- name: Download Cilium CLI
  register: download_cilium_cli
  shell: |
    curl -L --remote-name-all https://github.com/cilium/cilium-cli/releases/download/{{ cilium_cli_version }}/cilium-linux-amd64.tar.gz{,.sha256sum};
    sha256sum --check cilium-linux-amd64.tar.gz.sha256sum;
    tar xzvfC cilium-linux-amd64.tar.gz /usr/local/bin;
  when:
  - cilium_cli_installed.rc == 1 or cilium_cli.rc == 1

- name: Deploy Cilium
  shell: |
    export KUBECONFIG=/etc/rancher/k3s/k3s.yaml;
    cilium install --version {{ cilium_version }} {{ extra_cilium_args | default("") }};
  #when:
  #- cilium_cli_installed.rc == 0 or download_cilium_cli.rc == 0
  