---

  - name: Patch-file Anti-Affinity and Replicas CoreDNS
    template:
      src: "coredns-patch.yaml.j2"
      dest: "/tmp/coredns-patch.yaml"
      owner: root
      group: root
      mode: 0664

  - name: Apply Patch CoreDNS
    command: k3s kubectl patch -n kube-system deployment coredns --patch-file /tmp/coredns-patch.yaml