---

- name: WARNING - Cluster Init
  pause:
    prompt: |
      The cluster_init value is 'true'. Are you sure you want to continue?

      Press ENTER to continue or CTRL+C and A to abort...
  when: dangerzone.cluster_init == true

- name: WARNING - Longhorn Clean-up
  pause:
    prompt: |
      The longhorn_clean_dir value is 'true'. Are you sure you want to continue?

      Press ENTER to continue or CTRL+C and A to abort...
  when: dangerzone.longhorn_clean_dir == true