---

- name: Install default packages
  become: yes
  apt:
    name: "{{ base_packages }}"
    update_cache: yes
    state: present
    install_recommends: no

- name: Switch to the legacy variant of iptables because of a bug in the nft version
  alternatives:
    name: iptables
    path: /usr/sbin/iptables-legacy
    link: /etc/alternatives/iptables
  notify: Reboot host and wait for it to restart