---

- name: Install nfs-common
  register: nfs_installed
  apt:
    name: nfs-common
    update_cache: yes
    state: present
    install_recommends: no
  when: 
  - ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu' 