---

- name: Remove SWAP from /etc/fstab
  register: remove_swap
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'

- name: Disable SWAP
  shell: "swapoff -a"
  when: remove_swap is changed