---

- name: Disable SWAP permanently
  register: swapoff
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'

- name: Disable SWAP
  shell: "swapoff -a"
  when: swapoff is changed